INTERFACE
SUBROUTINE SUECRAD (KULOUT, KLEV, PETAH )
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KULOUT
REAL(KIND=JPRB) ,INTENT(IN) :: PETAH(KLEV+1)
INTEGER(KIND=JPIM), PARAMETER :: JP_MIN_HALO=5
INTEGER(KIND=JPIM), PARAMETER :: JPIOMASTER=1
END SUBROUTINE SUECRAD
END INTERFACE
