!! Output SPLA
! JE20141223
      IF(ok_chimeredust) CALL histwrite_phy(o_m1dflux,m1dflux)
      IF(ok_chimeredust) CALL histwrite_phy(o_m2dflux,m2dflux)
      IF(ok_chimeredust) CALL histwrite_phy(o_m3dflux,m3dflux)
! traceur

      CALL histwrite_phy( o_taue550          , diff_aod550_tot  )
      CALL histwrite_phy( o_taue670          , diag_aod670_tot  )
      CALL histwrite_phy( o_taue865          , diag_aod865_tot  ) 
      IF(id_fine>0) CALL histwrite_phy( o_taue550_tr2      , diff_aod550_tr2  )
      IF(id_fine>0) CALL histwrite_phy( o_taue670_tr2      , diag_aod670_tr2  )
      IF(id_fine>0) CALL histwrite_phy( o_taue865_tr2      , diag_aod865_tr2  )
      IF(id_coss>0) CALL histwrite_phy( o_taue550_ss       , diag_aod550_ss   )
      IF(id_coss>0) CALL histwrite_phy( o_taue670_ss       , diag_aod670_ss   )
      IF(id_coss>0) CALL histwrite_phy( o_taue865_ss       , diag_aod865_ss   )
      IF(id_codu>0) CALL histwrite_phy( o_taue550_dust     , diag_aod550_dust )
      IF(id_codu>0) CALL histwrite_phy( o_taue670_dust     , diag_aod670_dust )
      IF(id_codu>0) CALL histwrite_phy( o_taue865_dust     , diag_aod865_dust )
      IF(id_scdu>0) CALL histwrite_phy( o_taue550_dustsco  , diag_aod550_dustsco )
      IF(id_scdu>0) CALL histwrite_phy( o_taue670_dustsco  , diag_aod670_dustsco )
      IF(id_scdu>0) CALL histwrite_phy( o_taue865_dustsco  , diag_aod865_dustsco )
      CALL histwrite_phy( o_taue550_aqua     , aod550_aqua  )
      CALL histwrite_phy( o_taue550_terra    , aod550_terra )
      CALL histwrite_phy( o_taue670_aqua     , aod670_aqua  )
      CALL histwrite_phy( o_taue670_terra    , aod670_terra )
      CALL histwrite_phy( o_taue865_aqua     , aod865_aqua  )
      CALL histwrite_phy( o_taue865_terra    , aod865_terra )

      IF(id_fine>0) CALL histwrite_phy( o_taue550_fine_aqua     ,aod550_tr2_aqua   )
      IF(id_fine>0) CALL histwrite_phy( o_taue670_fine_aqua     ,aod670_tr2_aqua   )
      IF(id_fine>0) CALL histwrite_phy( o_taue865_fine_aqua     ,aod865_tr2_aqua   )
      IF(id_coss>0) CALL histwrite_phy( o_taue550_coss_aqua      ,aod550_ss_aqua   )
      IF(id_coss>0) CALL histwrite_phy( o_taue670_coss_aqua      ,aod670_ss_aqua   )
      IF(id_coss>0) CALL histwrite_phy( o_taue865_coss_aqua      ,aod865_ss_aqua   )
      IF(id_codu>0) CALL histwrite_phy( o_taue550_codu_aqua    ,aod550_dust_aqua   )
      IF(id_codu>0) CALL histwrite_phy( o_taue670_codu_aqua    ,aod670_dust_aqua   )
      IF(id_codu>0) CALL histwrite_phy( o_taue865_codu_aqua    ,aod865_dust_aqua   )
      IF(id_scdu>0) CALL histwrite_phy( o_taue670_scdu_aqua ,aod670_dustsco_aqua   )
      IF(id_scdu>0) CALL histwrite_phy( o_taue550_scdu_aqua ,aod550_dustsco_aqua   )
      IF(id_scdu>0) CALL histwrite_phy( o_taue865_scdu_aqua ,aod865_dustsco_aqua   )
      
      IF(id_fine>0) CALL histwrite_phy( o_taue550_fine_terra     ,aod550_tr2_terra   )
      IF(id_fine>0) CALL histwrite_phy( o_taue670_fine_terra     ,aod670_tr2_terra   )
      IF(id_fine>0) CALL histwrite_phy( o_taue865_fine_terra     ,aod865_tr2_terra   )
      IF(id_coss>0) CALL histwrite_phy( o_taue550_coss_terra      ,aod550_ss_terra   )
      IF(id_coss>0) CALL histwrite_phy( o_taue670_coss_terra      ,aod670_ss_terra   )
      IF(id_coss>0) CALL histwrite_phy( o_taue865_coss_terra      ,aod865_ss_terra   )
      IF(id_codu>0) CALL histwrite_phy( o_taue550_codu_terra    ,aod550_dust_terra   )
      IF(id_codu>0) CALL histwrite_phy( o_taue670_codu_terra    ,aod670_dust_terra   )
      IF(id_codu>0) CALL histwrite_phy( o_taue865_codu_terra    ,aod865_dust_terra   )
      IF(id_scdu>0) CALL histwrite_phy( o_taue670_scdu_terra ,aod670_dustsco_terra   )
      IF(id_scdu>0) CALL histwrite_phy( o_taue550_scdu_terra ,aod550_dustsco_terra   )
      IF(id_scdu>0) CALL histwrite_phy( o_taue865_scdu_terra ,aod865_dustsco_terra   )


      IF(id_prec>0) CALL histwrite_phy( o_trm01 , trm01 )
      IF(id_fine>0) CALL histwrite_phy( o_trm02 , trm02 )
      IF(id_coss>0) CALL histwrite_phy( o_trm03 , trm03 )
      IF(id_codu>0) CALL histwrite_phy( o_trm04 , trm04 )
      IF(id_scdu>0) CALL histwrite_phy( o_trm05 , trm05 )
      IF(id_prec>0) CALL histwrite_phy( o_sconc01 , sconc01 )
      IF(id_fine>0) CALL histwrite_phy( o_sconc02 , sconc02 )
      IF(id_coss>0) CALL histwrite_phy( o_sconc03 , sconc03 )
      IF(id_codu>0) CALL histwrite_phy( o_sconc04 , sconc04 )
      IF(id_scdu>0) CALL histwrite_phy( o_sconc05 , sconc05 )

! Lessivage

      IF(id_prec>0) CALL histwrite_phy( o_flux01       , flux01 )
      IF(id_fine>0) CALL histwrite_phy( o_flux02       , flux02 )
      IF(id_coss>0) CALL histwrite_phy( o_flux03       , flux03 )
      IF(id_codu>0) CALL histwrite_phy( o_flux04       , flux04 )
      IF(id_scdu>0) CALL histwrite_phy( o_flux05       , flux05 )
      IF(id_prec>0) CALL histwrite_phy( o_ds01         , ds01 )
      IF(id_fine>0) CALL histwrite_phy( o_ds02         , ds02 )
      IF(id_coss>0) CALL histwrite_phy( o_ds03         , ds03 )
      IF(id_codu>0) CALL histwrite_phy( o_ds04         , ds04 )
      IF(id_scdu>0) CALL histwrite_phy( o_ds05         , ds05 )
      IF(id_prec>0) CALL histwrite_phy( o_dh01         , dh01 )
      IF(id_fine>0) CALL histwrite_phy( o_dh02         , dh02 )
      IF(id_coss>0) CALL histwrite_phy( o_dh03         , dh03 )
      IF(id_codu>0) CALL histwrite_phy( o_dh04         , dh04 )
      IF(id_scdu>0) CALL histwrite_phy( o_dh05         , dh05 )
      IF(id_prec>0) CALL histwrite_phy( o_dtrconv01    , dtrconv01 )
      IF(id_fine>0) CALL histwrite_phy( o_dtrconv02    , dtrconv02 )
      IF(id_coss>0) CALL histwrite_phy( o_dtrconv03    , dtrconv03 )
      IF(id_codu>0) CALL histwrite_phy( o_dtrconv04    , dtrconv04 )
      IF(id_scdu>0) CALL histwrite_phy( o_dtrconv05    , dtrconv05 )
      IF(id_prec>0) CALL histwrite_phy( o_dtherm01     , dtherm01 )
      IF(id_fine>0) CALL histwrite_phy( o_dtherm02     , dtherm02 )
      IF(id_coss>0) CALL histwrite_phy( o_dtherm03     , dtherm03 )
      IF(id_codu>0) CALL histwrite_phy( o_dtherm04     , dtherm04 )
      IF(id_scdu>0) CALL histwrite_phy( o_dtherm05     , dtherm05 )
      IF(id_prec>0) CALL histwrite_phy( o_dhkecv01     , dhkecv01 )
      IF(id_fine>0) CALL histwrite_phy( o_dhkecv02     , dhkecv02 )
      IF(id_coss>0) CALL histwrite_phy( o_dhkecv03     , dhkecv03 )
      IF(id_codu>0) CALL histwrite_phy( o_dhkecv04     , dhkecv04 )
      IF(id_scdu>0) CALL histwrite_phy( o_dhkecv05     , dhkecv05 )
      IF(id_prec>0) CALL histwrite_phy( o_d_tr_ds01     , d_tr_ds01 )
      IF(id_fine>0) CALL histwrite_phy( o_d_tr_ds02     , d_tr_ds02 )
      IF(id_coss>0) CALL histwrite_phy( o_d_tr_ds03     , d_tr_ds03 )
      IF(id_codu>0) CALL histwrite_phy( o_d_tr_ds04     , d_tr_ds04 )
      IF(id_scdu>0) CALL histwrite_phy( o_d_tr_ds05     , d_tr_ds05 )
      IF(id_prec>0) CALL histwrite_phy( o_dhkelsc01    , dhkelsc01 )
      IF(id_fine>0) CALL histwrite_phy( o_dhkelsc02    , dhkelsc02 )
      IF(id_coss>0) CALL histwrite_phy( o_dhkelsc03    , dhkelsc03 )
      IF(id_codu>0) CALL histwrite_phy( o_dhkelsc04    , dhkelsc04 )
      IF(id_scdu>0) CALL histwrite_phy( o_dhkelsc05    , dhkelsc05 )
      IF(id_prec>0) CALL histwrite_phy( o_d_tr_cv01    , d_tr_cv01 )
      IF(id_fine>0) CALL histwrite_phy( o_d_tr_cv02    , d_tr_cv02 )
      IF(id_coss>0) CALL histwrite_phy( o_d_tr_cv03    , d_tr_cv03 )
      IF(id_codu>0) CALL histwrite_phy( o_d_tr_cv04    , d_tr_cv04 )
      IF(id_scdu>0) CALL histwrite_phy( o_d_tr_cv05    , d_tr_cv05 )
      IF(id_prec>0) CALL histwrite_phy( o_d_tr_trsp01  , d_tr_trsp01 )
      IF(id_fine>0) CALL histwrite_phy( o_d_tr_trsp02  , d_tr_trsp02 )
      IF(id_coss>0) CALL histwrite_phy( o_d_tr_trsp03  , d_tr_trsp03 )
      IF(id_codu>0) CALL histwrite_phy( o_d_tr_trsp04  , d_tr_trsp04 )
      IF(id_scdu>0) CALL histwrite_phy( o_d_tr_trsp05  , d_tr_trsp05 )
      IF(id_prec>0) CALL histwrite_phy( o_d_tr_sscav01 , d_tr_sscav01 )
      IF(id_fine>0) CALL histwrite_phy( o_d_tr_sscav02 , d_tr_sscav02 )
      IF(id_coss>0) CALL histwrite_phy( o_d_tr_sscav03 , d_tr_sscav03 )
      IF(id_codu>0) CALL histwrite_phy( o_d_tr_sscav04 , d_tr_sscav04 )
      IF(id_scdu>0) CALL histwrite_phy( o_d_tr_sscav05 , d_tr_sscav05 )
      IF(id_prec>0) CALL histwrite_phy( o_d_tr_sat01   , d_tr_sat01 )
      IF(id_fine>0) CALL histwrite_phy( o_d_tr_sat02   , d_tr_sat02 )
      IF(id_coss>0) CALL histwrite_phy( o_d_tr_sat03   , d_tr_sat03 )
      IF(id_codu>0) CALL histwrite_phy( o_d_tr_sat04   , d_tr_sat04 )
      IF(id_scdu>0) CALL histwrite_phy( o_d_tr_sat05   , d_tr_sat05 )
      IF(id_prec>0) CALL histwrite_phy( o_d_tr_uscav01 , d_tr_uscav01 )
      IF(id_fine>0) CALL histwrite_phy( o_d_tr_uscav02 , d_tr_uscav02 )
      IF(id_coss>0) CALL histwrite_phy( o_d_tr_uscav03 , d_tr_uscav03 )
      IF(id_codu>0) CALL histwrite_phy( o_d_tr_uscav04 , d_tr_uscav04 )
      IF(id_scdu>0) CALL histwrite_phy( o_d_tr_uscav05 , d_tr_uscav05 )
      IF(id_prec>0) CALL histwrite_phy( o_d_tr_insc01 , d_tr_insc01 )
      IF(id_fine>0) CALL histwrite_phy( o_d_tr_insc02 , d_tr_insc02 )
      IF(id_coss>0) CALL histwrite_phy( o_d_tr_insc03 , d_tr_insc03 )
      IF(id_codu>0) CALL histwrite_phy( o_d_tr_insc04 , d_tr_insc04 )
      IF(id_scdu>0) CALL histwrite_phy( o_d_tr_insc05 , d_tr_insc05 )
      IF(id_prec>0) CALL histwrite_phy( o_d_tr_bcscav01 , d_tr_bcscav01 )
      IF(id_fine>0) CALL histwrite_phy( o_d_tr_bcscav02 , d_tr_bcscav02 )
      IF(id_coss>0) CALL histwrite_phy( o_d_tr_bcscav03 , d_tr_bcscav03 )
      IF(id_codu>0) CALL histwrite_phy( o_d_tr_bcscav04 , d_tr_bcscav04 )
      IF(id_scdu>0) CALL histwrite_phy( o_d_tr_bcscav05 , d_tr_bcscav05 )
      IF(id_prec>0) CALL histwrite_phy( o_d_tr_evapls01 , d_tr_evapls01 )
      IF(id_fine>0) CALL histwrite_phy( o_d_tr_evapls02 , d_tr_evapls02 )
      IF(id_coss>0) CALL histwrite_phy( o_d_tr_evapls03 , d_tr_evapls03 )
      IF(id_codu>0) CALL histwrite_phy( o_d_tr_evapls04 , d_tr_evapls04 )
      IF(id_scdu>0) CALL histwrite_phy( o_d_tr_evapls05 , d_tr_evapls05 )
      IF(id_prec>0) CALL histwrite_phy( o_d_tr_ls01 , d_tr_ls01 )
      IF(id_fine>0) CALL histwrite_phy( o_d_tr_ls02 , d_tr_ls02 )
      IF(id_coss>0) CALL histwrite_phy( o_d_tr_ls03 , d_tr_ls03 )
      IF(id_codu>0) CALL histwrite_phy( o_d_tr_ls04 , d_tr_ls04 )
      IF(id_scdu>0) CALL histwrite_phy( o_d_tr_ls05 , d_tr_ls05 )

      IF(id_prec>0) CALL histwrite_phy( o_d_tr_dyn01 , d_tr_dyn01 )
      IF(id_fine>0) CALL histwrite_phy( o_d_tr_dyn02 , d_tr_dyn02 )
      IF(id_coss>0) CALL histwrite_phy( o_d_tr_dyn03 , d_tr_dyn03 )
      IF(id_codu>0) CALL histwrite_phy( o_d_tr_dyn04 , d_tr_dyn04 )
      IF(id_scdu>0) CALL histwrite_phy( o_d_tr_dyn05 , d_tr_dyn05 )
      
      IF(id_prec>0) CALL histwrite_phy( o_d_tr_cl01 , d_tr_cl01 )
      IF(id_fine>0) CALL histwrite_phy( o_d_tr_cl02 , d_tr_cl02 )
      IF(id_coss>0) CALL histwrite_phy( o_d_tr_cl03 , d_tr_cl03 )
      IF(id_codu>0) CALL histwrite_phy( o_d_tr_cl04 , d_tr_cl04 )
      IF(id_scdu>0) CALL histwrite_phy( o_d_tr_cl05 , d_tr_cl05 )
      IF(id_prec>0) CALL histwrite_phy( o_d_tr_th01 , d_tr_th01 )
      IF(id_fine>0) CALL histwrite_phy( o_d_tr_th02 , d_tr_th02 )
      IF(id_coss>0) CALL histwrite_phy( o_d_tr_th03 , d_tr_th03 )
      IF(id_codu>0) CALL histwrite_phy( o_d_tr_th04 , d_tr_th04 )
      IF(id_scdu>0) CALL histwrite_phy( o_d_tr_th05 , d_tr_th05 )

      IF(id_coss>0) CALL histwrite_phy( o_sed_ss , sed_ss)
      IF(id_codu>0) CALL histwrite_phy( o_sed_dust , sed_dust)
      IF(id_scdu>0) CALL histwrite_phy( o_sed_dustsco , sed_dustsco)
      IF(id_prec>0) CALL histwrite_phy( o_g2p_gas , his_g2pgas )
      IF(id_fine>0) CALL histwrite_phy( o_g2p_aer , his_g2paer)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      IF(id_coss>0) CALL histwrite_phy( o_sed_ss3D , sed_ss3D)
      IF(id_codu>0) CALL histwrite_phy( o_sed_dust3D , sed_dust3D)
      IF(id_scdu>0) CALL histwrite_phy( o_sed_dustsco3D , sed_dustsco3D)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! histrac_spl
!
      CALL histwrite_phy( o_fluxbb              , fluxbb               )
      CALL histwrite_phy( o_fluxff              , fluxff               )
      CALL histwrite_phy( o_fluxbcbb            , fluxbcbb             )
      CALL histwrite_phy( o_fluxbcff            , fluxbcff             )
      CALL histwrite_phy( o_fluxbcnff           , fluxbcnff            )
      CALL histwrite_phy( o_fluxbcba            , fluxbcba             )
      CALL histwrite_phy( o_fluxbc              , fluxbc               )
      CALL histwrite_phy( o_fluxombb            , fluxombb             )
      CALL histwrite_phy( o_fluxomff            , fluxomff             )
      CALL histwrite_phy( o_fluxomnff           , fluxomnff            )
      CALL histwrite_phy( o_fluxomba            , fluxomba             )
      CALL histwrite_phy( o_fluxomnat           , fluxomnat            )
      CALL histwrite_phy( o_fluxom              , fluxom               )
      CALL histwrite_phy( o_fluxh2sff           , fluxh2sff            )
      CALL histwrite_phy( o_fluxh2snff          , fluxh2snff           )
      CALL histwrite_phy( o_fluxso2ff           , fluxso2ff            )
      CALL histwrite_phy( o_fluxso2nff          , fluxso2nff           )
      CALL histwrite_phy( o_fluxso2bb           , fluxso2bb            )
      CALL histwrite_phy( o_fluxso2vol          , fluxso2vol           )
      CALL histwrite_phy( o_fluxso2ba           , fluxso2ba            )
      CALL histwrite_phy( o_fluxso2             , fluxso2              )
      CALL histwrite_phy( o_fluxso4ff           , fluxso4ff            )
      CALL histwrite_phy( o_fluxso4nff          , fluxso4nff           )
      CALL histwrite_phy( o_fluxso4bb           , fluxso4bb            )
      CALL histwrite_phy( o_fluxso4ba           , fluxso4ba            )
      CALL histwrite_phy( o_fluxso4             , fluxso4              )
      CALL histwrite_phy( o_fluxdms             , fluxdms              )
      CALL histwrite_phy( o_fluxh2sbio          , fluxh2sbio           )
      CALL histwrite_phy( o_fluxdustec          , fluxdustec           )
      CALL histwrite_phy( o_fluxddfine          , fluxddfine           )
      CALL histwrite_phy( o_fluxddcoa           , fluxddcoa            )
      CALL histwrite_phy( o_fluxddsco           , fluxddsco            )
      CALL histwrite_phy( o_fluxdd              , fluxdd               )
      CALL histwrite_phy( o_fluxssfine          , fluxssfine           )
      CALL histwrite_phy( o_fluxsscoa           , fluxsscoa            )
      CALL histwrite_phy( o_fluxss              , fluxss               )
      CALL histwrite_phy( o_flux_sparam_ind     , flux_sparam_ind      )
      CALL histwrite_phy( o_flux_sparam_bb      , flux_sparam_bb       )
      CALL histwrite_phy( o_flux_sparam_ff      , flux_sparam_ff       )
      CALL histwrite_phy( o_flux_sparam_ddfine  , flux_sparam_ddfine   )
      CALL histwrite_phy( o_flux_sparam_ddcoa   , flux_sparam_ddcoa    )
      CALL histwrite_phy( o_flux_sparam_ddsco   , flux_sparam_ddsco    )
      CALL histwrite_phy( o_flux_sparam_ssfine  , flux_sparam_ssfine   )
      CALL histwrite_phy( o_flux_sparam_sscoa   , flux_sparam_sscoa    )
      CALL histwrite_phy( o_u10m_ss             , u10m_ss              )
      CALL histwrite_phy( o_v10m_ss             , v10m_ss              )
